// Code generated by goctl. DO NOT EDIT.
// Source: judge.proto

package server

import (
	"context"

	"YunOJ/services/judge/rpc/internal/logic"
	"YunOJ/services/judge/rpc/internal/svc"
	"YunOJ/services/judge/rpc/judge"
)

type JudgeServiceServer struct {
	svcCtx *svc.ServiceContext
	judge.UnimplementedJudgeServiceServer
}

func NewJudgeServiceServer(svcCtx *svc.ServiceContext) *JudgeServiceServer {
	return &JudgeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *JudgeServiceServer) Judge(ctx context.Context, in *judge.JudgeRequest) (*judge.JudgeResponse, error) {
	l := logic.NewJudgeLogic(ctx, s.svcCtx)
	return l.Judge(in)
}

func (s *JudgeServiceServer) AddJudgeCases(ctx context.Context, in *judge.AddJudgeCasesRequest) (*judge.AddJudgeCasesResponse, error) {
	l := logic.NewAddJudgeCasesLogic(ctx, s.svcCtx)
	return l.AddJudgeCases(in)
}

func (s *JudgeServiceServer) UpdateJudgeCase(ctx context.Context, in *judge.UpdateJudgeCaseRequest) (*judge.UpdateJudgeCaseResponse, error) {
	l := logic.NewUpdateJudgeCaseLogic(ctx, s.svcCtx)
	return l.UpdateJudgeCase(in)
}

func (s *JudgeServiceServer) GetJudgeCaseIdsByProblemId(ctx context.Context, in *judge.GetJudgeCaseIdsByProblemIdRequest) (*judge.GetJudgeCaseIdsByProblemIdResponse, error) {
	l := logic.NewGetJudgeCaseIdsByProblemIdLogic(ctx, s.svcCtx)
	return l.GetJudgeCaseIdsByProblemId(in)
}

func (s *JudgeServiceServer) DeleteJudgeCaseByCaseId(ctx context.Context, in *judge.DeleteJudgeCaseByCaseIdRequest) (*judge.DeleteJudgeCaseByCaseIdResponse, error) {
	l := logic.NewDeleteJudgeCaseByCaseIdLogic(ctx, s.svcCtx)
	return l.DeleteJudgeCaseByCaseId(in)
}
