// Code generated by goctl. DO NOT EDIT.
// Source: judge.proto

package server

import (
	"context"

	"YunOJ/services/judge/rpc/internal/logic"
	"YunOJ/services/judge/rpc/internal/svc"
	"YunOJ/services/judge/rpc/judge"
)

type JudgeServiceServer struct {
	svcCtx *svc.ServiceContext
	judge.UnimplementedJudgeServiceServer
}

func NewJudgeServiceServer(svcCtx *svc.ServiceContext) *JudgeServiceServer {
	return &JudgeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *JudgeServiceServer) Judge(ctx context.Context, in *judge.JudgeRequest) (*judge.JudgeResponse, error) {
	l := logic.NewJudgeLogic(ctx, s.svcCtx)
	return l.Judge(in)
}

func (s *JudgeServiceServer) AddJudgeCases(ctx context.Context, in *judge.AddJudgeCasesRequest) (*judge.AddJudgeCasesResponse, error) {
	l := logic.NewAddJudgeCasesLogic(ctx, s.svcCtx)
	return l.AddJudgeCases(in)
}

func (s *JudgeServiceServer) GetJudgeCasePathsByProblemId(ctx context.Context, in *judge.GetJudgeCasePathsRequest) (*judge.GetJudgeCasePathsResponse, error) {
	l := logic.NewGetJudgeCasePathsByProblemIdLogic(ctx, s.svcCtx)
	return l.GetJudgeCasePathsByProblemId(in)
}

func (s *JudgeServiceServer) DeleteJudgeCaseByProblemId(ctx context.Context, in *judge.DeleteJudgeCaseByProblemIdRequest) (*judge.DeleteJudgeCaseByProblemIdResponse, error) {
	l := logic.NewDeleteJudgeCaseByProblemIdLogic(ctx, s.svcCtx)
	return l.DeleteJudgeCaseByProblemId(in)
}
