// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: judge.proto

package judge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	JudgeService_Judge_FullMethodName                      = "/judge.JudgeService/Judge"
	JudgeService_AddJudgeCases_FullMethodName              = "/judge.JudgeService/AddJudgeCases"
	JudgeService_UpdateJudgeCase_FullMethodName            = "/judge.JudgeService/UpdateJudgeCase"
	JudgeService_GetJudgeCaseIdsByProblemId_FullMethodName = "/judge.JudgeService/GetJudgeCaseIdsByProblemId"
	JudgeService_DeleteJudgeCaseByCaseId_FullMethodName    = "/judge.JudgeService/DeleteJudgeCaseByCaseId"
)

// JudgeServiceClient is the client API for JudgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JudgeServiceClient interface {
	Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error)
	AddJudgeCases(ctx context.Context, in *AddJudgeCasesRequest, opts ...grpc.CallOption) (*AddJudgeCasesResponse, error)
	UpdateJudgeCase(ctx context.Context, in *UpdateJudgeCaseRequest, opts ...grpc.CallOption) (*UpdateJudgeCaseResponse, error)
	GetJudgeCaseIdsByProblemId(ctx context.Context, in *GetJudgeCaseIdsByProblemIdRequest, opts ...grpc.CallOption) (*GetJudgeCaseIdsByProblemIdResponse, error)
	DeleteJudgeCaseByCaseId(ctx context.Context, in *DeleteJudgeCaseByCaseIdRequest, opts ...grpc.CallOption) (*DeleteJudgeCaseByCaseIdResponse, error)
}

type judgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeServiceClient(cc grpc.ClientConnInterface) JudgeServiceClient {
	return &judgeServiceClient{cc}
}

func (c *judgeServiceClient) Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error) {
	out := new(JudgeResponse)
	err := c.cc.Invoke(ctx, JudgeService_Judge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) AddJudgeCases(ctx context.Context, in *AddJudgeCasesRequest, opts ...grpc.CallOption) (*AddJudgeCasesResponse, error) {
	out := new(AddJudgeCasesResponse)
	err := c.cc.Invoke(ctx, JudgeService_AddJudgeCases_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) UpdateJudgeCase(ctx context.Context, in *UpdateJudgeCaseRequest, opts ...grpc.CallOption) (*UpdateJudgeCaseResponse, error) {
	out := new(UpdateJudgeCaseResponse)
	err := c.cc.Invoke(ctx, JudgeService_UpdateJudgeCase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) GetJudgeCaseIdsByProblemId(ctx context.Context, in *GetJudgeCaseIdsByProblemIdRequest, opts ...grpc.CallOption) (*GetJudgeCaseIdsByProblemIdResponse, error) {
	out := new(GetJudgeCaseIdsByProblemIdResponse)
	err := c.cc.Invoke(ctx, JudgeService_GetJudgeCaseIdsByProblemId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) DeleteJudgeCaseByCaseId(ctx context.Context, in *DeleteJudgeCaseByCaseIdRequest, opts ...grpc.CallOption) (*DeleteJudgeCaseByCaseIdResponse, error) {
	out := new(DeleteJudgeCaseByCaseIdResponse)
	err := c.cc.Invoke(ctx, JudgeService_DeleteJudgeCaseByCaseId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeServiceServer is the server API for JudgeService service.
// All implementations must embed UnimplementedJudgeServiceServer
// for forward compatibility
type JudgeServiceServer interface {
	Judge(context.Context, *JudgeRequest) (*JudgeResponse, error)
	AddJudgeCases(context.Context, *AddJudgeCasesRequest) (*AddJudgeCasesResponse, error)
	UpdateJudgeCase(context.Context, *UpdateJudgeCaseRequest) (*UpdateJudgeCaseResponse, error)
	GetJudgeCaseIdsByProblemId(context.Context, *GetJudgeCaseIdsByProblemIdRequest) (*GetJudgeCaseIdsByProblemIdResponse, error)
	DeleteJudgeCaseByCaseId(context.Context, *DeleteJudgeCaseByCaseIdRequest) (*DeleteJudgeCaseByCaseIdResponse, error)
	mustEmbedUnimplementedJudgeServiceServer()
}

// UnimplementedJudgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJudgeServiceServer struct {
}

func (UnimplementedJudgeServiceServer) Judge(context.Context, *JudgeRequest) (*JudgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Judge not implemented")
}
func (UnimplementedJudgeServiceServer) AddJudgeCases(context.Context, *AddJudgeCasesRequest) (*AddJudgeCasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJudgeCases not implemented")
}
func (UnimplementedJudgeServiceServer) UpdateJudgeCase(context.Context, *UpdateJudgeCaseRequest) (*UpdateJudgeCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJudgeCase not implemented")
}
func (UnimplementedJudgeServiceServer) GetJudgeCaseIdsByProblemId(context.Context, *GetJudgeCaseIdsByProblemIdRequest) (*GetJudgeCaseIdsByProblemIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJudgeCaseIdsByProblemId not implemented")
}
func (UnimplementedJudgeServiceServer) DeleteJudgeCaseByCaseId(context.Context, *DeleteJudgeCaseByCaseIdRequest) (*DeleteJudgeCaseByCaseIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJudgeCaseByCaseId not implemented")
}
func (UnimplementedJudgeServiceServer) mustEmbedUnimplementedJudgeServiceServer() {}

// UnsafeJudgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeServiceServer will
// result in compilation errors.
type UnsafeJudgeServiceServer interface {
	mustEmbedUnimplementedJudgeServiceServer()
}

func RegisterJudgeServiceServer(s grpc.ServiceRegistrar, srv JudgeServiceServer) {
	s.RegisterService(&JudgeService_ServiceDesc, srv)
}

func _JudgeService_Judge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JudgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).Judge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_Judge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).Judge(ctx, req.(*JudgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_AddJudgeCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJudgeCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).AddJudgeCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_AddJudgeCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).AddJudgeCases(ctx, req.(*AddJudgeCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_UpdateJudgeCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJudgeCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).UpdateJudgeCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_UpdateJudgeCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).UpdateJudgeCase(ctx, req.(*UpdateJudgeCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_GetJudgeCaseIdsByProblemId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJudgeCaseIdsByProblemIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).GetJudgeCaseIdsByProblemId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_GetJudgeCaseIdsByProblemId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).GetJudgeCaseIdsByProblemId(ctx, req.(*GetJudgeCaseIdsByProblemIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_DeleteJudgeCaseByCaseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJudgeCaseByCaseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).DeleteJudgeCaseByCaseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_DeleteJudgeCaseByCaseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).DeleteJudgeCaseByCaseId(ctx, req.(*DeleteJudgeCaseByCaseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JudgeService_ServiceDesc is the grpc.ServiceDesc for JudgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JudgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "judge.JudgeService",
	HandlerType: (*JudgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Judge",
			Handler:    _JudgeService_Judge_Handler,
		},
		{
			MethodName: "AddJudgeCases",
			Handler:    _JudgeService_AddJudgeCases_Handler,
		},
		{
			MethodName: "UpdateJudgeCase",
			Handler:    _JudgeService_UpdateJudgeCase_Handler,
		},
		{
			MethodName: "GetJudgeCaseIdsByProblemId",
			Handler:    _JudgeService_GetJudgeCaseIdsByProblemId_Handler,
		},
		{
			MethodName: "DeleteJudgeCaseByCaseId",
			Handler:    _JudgeService_DeleteJudgeCaseByCaseId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judge.proto",
}
