// Code generated by goctl. DO NOT EDIT.
// Source: judge.proto

package judgeservice

import (
	"context"

	"YunOJ/services/judge/rpc/judge"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddJudgeCasesRequest               = judge.AddJudgeCasesRequest
	AddJudgeCasesResponse              = judge.AddJudgeCasesResponse
	DeleteJudgeCaseByProblemIdRequest  = judge.DeleteJudgeCaseByProblemIdRequest
	DeleteJudgeCaseByProblemIdResponse = judge.DeleteJudgeCaseByProblemIdResponse
	GetJudgeCasePathsRequest           = judge.GetJudgeCasePathsRequest
	GetJudgeCasePathsResponse          = judge.GetJudgeCasePathsResponse
	JudgeCase                          = judge.JudgeCase
	JudgeRequest                       = judge.JudgeRequest
	JudgeResponse                      = judge.JudgeResponse
	OnlineJudgeRequest                 = judge.OnlineJudgeRequest
	OnlineJudgeResponse                = judge.OnlineJudgeResponse

	JudgeService interface {
		Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error)
		OnlineJudge(ctx context.Context, in *OnlineJudgeRequest, opts ...grpc.CallOption) (*OnlineJudgeResponse, error)
		AddJudgeCases(ctx context.Context, in *AddJudgeCasesRequest, opts ...grpc.CallOption) (*AddJudgeCasesResponse, error)
		GetJudgeCasePathsByProblemId(ctx context.Context, in *GetJudgeCasePathsRequest, opts ...grpc.CallOption) (*GetJudgeCasePathsResponse, error)
		DeleteJudgeCaseByProblemId(ctx context.Context, in *DeleteJudgeCaseByProblemIdRequest, opts ...grpc.CallOption) (*DeleteJudgeCaseByProblemIdResponse, error)
	}

	defaultJudgeService struct {
		cli zrpc.Client
	}
)

func NewJudgeService(cli zrpc.Client) JudgeService {
	return &defaultJudgeService{
		cli: cli,
	}
}

func (m *defaultJudgeService) Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error) {
	client := judge.NewJudgeServiceClient(m.cli.Conn())
	return client.Judge(ctx, in, opts...)
}

func (m *defaultJudgeService) OnlineJudge(ctx context.Context, in *OnlineJudgeRequest, opts ...grpc.CallOption) (*OnlineJudgeResponse, error) {
	client := judge.NewJudgeServiceClient(m.cli.Conn())
	return client.OnlineJudge(ctx, in, opts...)
}

func (m *defaultJudgeService) AddJudgeCases(ctx context.Context, in *AddJudgeCasesRequest, opts ...grpc.CallOption) (*AddJudgeCasesResponse, error) {
	client := judge.NewJudgeServiceClient(m.cli.Conn())
	return client.AddJudgeCases(ctx, in, opts...)
}

func (m *defaultJudgeService) GetJudgeCasePathsByProblemId(ctx context.Context, in *GetJudgeCasePathsRequest, opts ...grpc.CallOption) (*GetJudgeCasePathsResponse, error) {
	client := judge.NewJudgeServiceClient(m.cli.Conn())
	return client.GetJudgeCasePathsByProblemId(ctx, in, opts...)
}

func (m *defaultJudgeService) DeleteJudgeCaseByProblemId(ctx context.Context, in *DeleteJudgeCaseByProblemIdRequest, opts ...grpc.CallOption) (*DeleteJudgeCaseByProblemIdResponse, error) {
	client := judge.NewJudgeServiceClient(m.cli.Conn())
	return client.DeleteJudgeCaseByProblemId(ctx, in, opts...)
}
