// Code generated by goctl. DO NOT EDIT.
// Source: test.proto

package server

import (
	"context"

	"YunOJ/services/test/rpc/internal/logic"
	"YunOJ/services/test/rpc/internal/svc"
	"YunOJ/services/test/rpc/test"
)

type TestServer struct {
	svcCtx *svc.ServiceContext
	test.UnimplementedTestServer
}

func NewTestServer(svcCtx *svc.ServiceContext) *TestServer {
	return &TestServer{
		svcCtx: svcCtx,
	}
}

func (s *TestServer) GetOne(ctx context.Context, in *test.GetOneReq) (*test.GetOneResp, error) {
	l := logic.NewGetOneLogic(ctx, s.svcCtx)
	return l.GetOne(in)
}
