// Code generated by goctl. DO NOT EDIT.
// Source: problem.proto

package server

import (
	"context"

	"YunOJ/services/problem/rpc/internal/logic"
	"YunOJ/services/problem/rpc/internal/svc"
	"YunOJ/services/problem/rpc/problem"
)

type ProblemServiceServer struct {
	svcCtx *svc.ServiceContext
	problem.UnimplementedProblemServiceServer
}

func NewProblemServiceServer(svcCtx *svc.ServiceContext) *ProblemServiceServer {
	return &ProblemServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProblemServiceServer) GetProblemById(ctx context.Context, in *problem.GetProblemByIdRequest) (*problem.GetProblemByIdResponse, error) {
	l := logic.NewGetProblemByIdLogic(ctx, s.svcCtx)
	return l.GetProblemById(in)
}

func (s *ProblemServiceServer) GetProblemsByPage(ctx context.Context, in *problem.GetProblemsByPageRequest) (*problem.GetProblemsByPageResponse, error) {
	l := logic.NewGetProblemsByPageLogic(ctx, s.svcCtx)
	return l.GetProblemsByPage(in)
}

func (s *ProblemServiceServer) CreateProblem(ctx context.Context, in *problem.CreateProblemRequest) (*problem.CreateProblemResponse, error) {
	l := logic.NewCreateProblemLogic(ctx, s.svcCtx)
	return l.CreateProblem(in)
}

func (s *ProblemServiceServer) UpdateProblem(ctx context.Context, in *problem.UpdateProblemRequest) (*problem.UpdateProblemResponse, error) {
	l := logic.NewUpdateProblemLogic(ctx, s.svcCtx)
	return l.UpdateProblem(in)
}

func (s *ProblemServiceServer) DeleteProblem(ctx context.Context, in *problem.DeleteProblemRequest) (*problem.DeleteProblemResponse, error) {
	l := logic.NewDeleteProblemLogic(ctx, s.svcCtx)
	return l.DeleteProblem(in)
}

func (s *ProblemServiceServer) CreateSubmit(ctx context.Context, in *problem.CreateSubmitRequest) (*problem.CreateSubmitResponse, error) {
	l := logic.NewCreateSubmitLogic(ctx, s.svcCtx)
	return l.CreateSubmit(in)
}

func (s *ProblemServiceServer) GetSubmitByUserIdAndProblemId(ctx context.Context, in *problem.GetSubmitByUserIdAndProblemIdRequest) (*problem.GetSubmitByUserIdAndProblemIdResponse, error) {
	l := logic.NewGetSubmitByUserIdAndProblemIdLogic(ctx, s.svcCtx)
	return l.GetSubmitByUserIdAndProblemId(in)
}
