// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"YunOJ/services/user/rpc/internal/logic"
	"YunOJ/services/user/rpc/internal/svc"
	"YunOJ/services/user/rpc/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) RegisterByPhone(ctx context.Context, in *user.RegisterByPhoneRequest) (*user.RegisterByPhoneResponse, error) {
	l := logic.NewRegisterByPhoneLogic(ctx, s.svcCtx)
	return l.RegisterByPhone(in)
}

func (s *UserServiceServer) LoginByPhone(ctx context.Context, in *user.LoginByPhoneRequest) (*user.LoginByPhoneResponse, error) {
	l := logic.NewLoginByPhoneLogic(ctx, s.svcCtx)
	return l.LoginByPhone(in)
}
