// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	contestRankInfoFieldNames          = builder.RawFieldNames(&ContestRankInfo{})
	contestRankInfoRows                = strings.Join(contestRankInfoFieldNames, ",")
	contestRankInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(contestRankInfoFieldNames, "`contest_rank_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	contestRankInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(contestRankInfoFieldNames, "`contest_rank_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheContestRankInfoContestRankIdPrefix            = "cache:contestRankInfo:contestRankId:"
	cacheContestRankInfoContestIdUserIdProblemIdPrefix = "cache:contestRankInfo:contestId:userId:problemId:"
)

type (
	contestRankInfoModel interface {
		Insert(ctx context.Context, data *ContestRankInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ContestRankInfo, error)
		FindByContestId(ctx context.Context, contestId int64) ([]ContestRankInfo, error)
		FindOneByContestIdUserIdProblemId(ctx context.Context, contestId int64, userId int64, problemId int64) (*ContestRankInfo, error)
		Update(ctx context.Context, data *ContestRankInfo) error
		Delete(ctx context.Context, contestRankId int64) error
	}

	defaultContestRankInfoModel struct {
		sqlc.CachedConn
		table string
	}

	ContestRankInfo struct {
		ContestRankId int64         `db:"contest_rank_id"` // 竞赛排名信息ID
		ContestId     int64         `db:"contest_id"`      // 竞赛ID
		UserId        int64         `db:"user_id"`         // 用户ID
		UserName      string        `db:"user_name"`       // 用户名称
		ProblemId     int64         `db:"problem_id"`      // 题目ID
		SubmitTimes   int64         `db:"submit_times"`    // 提交次数
		TryTimes      int64         `db:"try_times"`       // 尝试次数
		IsPass        bool          `db:"is_pass"`         // 是否通过
		FirstPassTime sql.NullInt64 `db:"first_pass_time"` // 首次通过时间 单位s
		CreatedAt     time.Time     `db:"created_at"`      // 记录创建时间
		UpdatedAt     time.Time     `db:"updated_at"`      // 记录更新时间
	}
)

func newContestRankInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultContestRankInfoModel {
	return &defaultContestRankInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`contest_rank_info`",
	}
}

func (m *defaultContestRankInfoModel) Delete(ctx context.Context, contestRankId int64) error {
	data, err := m.FindOne(ctx, contestRankId)
	if err != nil {
		return err
	}

	contestRankInfoContestIdUserIdProblemIdKey := fmt.Sprintf("%s%v:%v:%v", cacheContestRankInfoContestIdUserIdProblemIdPrefix, data.ContestId, data.UserId, data.ProblemId)
	contestRankInfoContestRankIdKey := fmt.Sprintf("%s%v", cacheContestRankInfoContestRankIdPrefix, contestRankId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `contest_rank_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, contestRankId)
	}, contestRankInfoContestIdUserIdProblemIdKey, contestRankInfoContestRankIdKey)
	return err
}

func (m *defaultContestRankInfoModel) FindOne(ctx context.Context, contestRankId int64) (*ContestRankInfo, error) {
	contestRankInfoContestRankIdKey := fmt.Sprintf("%s%v", cacheContestRankInfoContestRankIdPrefix, contestRankId)
	var resp ContestRankInfo
	err := m.QueryRowCtx(ctx, &resp, contestRankInfoContestRankIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `contest_rank_id` = ? limit 1", contestRankInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, contestRankId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContestRankInfoModel) FindByContestId(ctx context.Context, contestId int64) ([]ContestRankInfo, error) {
	var resp []ContestRankInfo
	query := fmt.Sprintf("select %s from %s where `contest_id` = ?", contestRankInfoRows, m.table)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, contestId)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContestRankInfoModel) FindOneByContestIdUserIdProblemId(ctx context.Context, contestId int64, userId int64, problemId int64) (*ContestRankInfo, error) {
	contestRankInfoContestIdUserIdProblemIdKey := fmt.Sprintf("%s%v:%v:%v", cacheContestRankInfoContestIdUserIdProblemIdPrefix, contestId, userId, problemId)
	var resp ContestRankInfo
	err := m.QueryRowIndexCtx(ctx, &resp, contestRankInfoContestIdUserIdProblemIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `contest_id` = ? and `user_id` = ? and `problem_id` = ? limit 1", contestRankInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, contestId, userId, problemId); err != nil {
			return nil, err
		}
		return resp.ContestRankId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContestRankInfoModel) Insert(ctx context.Context, data *ContestRankInfo) (sql.Result, error) {
	contestRankInfoContestIdUserIdProblemIdKey := fmt.Sprintf("%s%v:%v:%v", cacheContestRankInfoContestIdUserIdProblemIdPrefix, data.ContestId, data.UserId, data.ProblemId)
	contestRankInfoContestRankIdKey := fmt.Sprintf("%s%v", cacheContestRankInfoContestRankIdPrefix, data.ContestRankId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, contestRankInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ContestId, data.UserId, data.UserName, data.ProblemId, data.SubmitTimes, data.TryTimes, data.IsPass, data.FirstPassTime)
	}, contestRankInfoContestIdUserIdProblemIdKey, contestRankInfoContestRankIdKey)
	return ret, err
}

func (m *defaultContestRankInfoModel) Update(ctx context.Context, newData *ContestRankInfo) error {
	data, err := m.FindOne(ctx, newData.ContestRankId)
	if err != nil {
		return err
	}

	contestRankInfoContestIdUserIdProblemIdKey := fmt.Sprintf("%s%v:%v:%v", cacheContestRankInfoContestIdUserIdProblemIdPrefix, data.ContestId, data.UserId, data.ProblemId)
	contestRankInfoContestRankIdKey := fmt.Sprintf("%s%v", cacheContestRankInfoContestRankIdPrefix, data.ContestRankId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `contest_rank_id` = ?", m.table, contestRankInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ContestId, newData.UserId, newData.UserName, newData.ProblemId, newData.SubmitTimes, newData.TryTimes, newData.IsPass, newData.FirstPassTime, newData.ContestRankId)
	}, contestRankInfoContestIdUserIdProblemIdKey, contestRankInfoContestRankIdKey)
	return err
}

func (m *defaultContestRankInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheContestRankInfoContestRankIdPrefix, primary)
}

func (m *defaultContestRankInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `contest_rank_id` = ? limit 1", contestRankInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultContestRankInfoModel) tableName() string {
	return m.table
}
