// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	contestProblemInfoFieldNames          = builder.RawFieldNames(&ContestProblemInfo{})
	contestProblemInfoRows                = strings.Join(contestProblemInfoFieldNames, ",")
	contestProblemInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(contestProblemInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	contestProblemInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(contestProblemInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheContestProblemInfoIdPrefix                 = "cache:contestProblemInfo:id:"
	cacheContestProblemInfoContestIdProblemIdPrefix = "cache:contestProblemInfo:contestId:problemId:"
	cacheContestProblemInfoProblemIdPrefix          = "cache:contestProblemInfo:problemId:"
)

type (
	contestProblemInfoModel interface {
		Insert(ctx context.Context, data *ContestProblemInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ContestProblemInfo, error)
		FindOneByContestIdProblemId(ctx context.Context, contestId int64, problemId int64) (*ContestProblemInfo, error)
		FindOneByProblemId(ctx context.Context, problemId int64) (*ContestProblemInfo, error)
		Update(ctx context.Context, data *ContestProblemInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultContestProblemInfoModel struct {
		sqlc.CachedConn
		table string
	}

	ContestProblemInfo struct {
		Id        int64     `db:"id"`         // ID
		ProblemId int64     `db:"problem_id"` // 题目ID
		ContestId int64     `db:"contest_id"` // 竞赛ID
		CreatedAt time.Time `db:"created_at"` // 记录创建时间
		UpdatedAt time.Time `db:"updated_at"` // 记录更新时间
	}
)

func newContestProblemInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultContestProblemInfoModel {
	return &defaultContestProblemInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`contest_problem_info`",
	}
}

func (m *defaultContestProblemInfoModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	contestProblemInfoContestIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheContestProblemInfoContestIdProblemIdPrefix, data.ContestId, data.ProblemId)
	contestProblemInfoIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoIdPrefix, id)
	contestProblemInfoProblemIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoProblemIdPrefix, data.ProblemId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, contestProblemInfoContestIdProblemIdKey, contestProblemInfoIdKey, contestProblemInfoProblemIdKey)
	return err
}

func (m *defaultContestProblemInfoModel) FindOne(ctx context.Context, id int64) (*ContestProblemInfo, error) {
	contestProblemInfoIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoIdPrefix, id)
	var resp ContestProblemInfo
	err := m.QueryRowCtx(ctx, &resp, contestProblemInfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", contestProblemInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContestProblemInfoModel) FindOneByContestIdProblemId(ctx context.Context, contestId int64, problemId int64) (*ContestProblemInfo, error) {
	contestProblemInfoContestIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheContestProblemInfoContestIdProblemIdPrefix, contestId, problemId)
	var resp ContestProblemInfo
	err := m.QueryRowIndexCtx(ctx, &resp, contestProblemInfoContestIdProblemIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `contest_id` = ? and `problem_id` = ? limit 1", contestProblemInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, contestId, problemId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContestProblemInfoModel) FindOneByProblemId(ctx context.Context, problemId int64) (*ContestProblemInfo, error) {
	contestProblemInfoProblemIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoProblemIdPrefix, problemId)
	var resp ContestProblemInfo
	err := m.QueryRowIndexCtx(ctx, &resp, contestProblemInfoProblemIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `problem_id` = ? limit 1", contestProblemInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, problemId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContestProblemInfoModel) Insert(ctx context.Context, data *ContestProblemInfo) (sql.Result, error) {
	contestProblemInfoContestIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheContestProblemInfoContestIdProblemIdPrefix, data.ContestId, data.ProblemId)
	contestProblemInfoIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoIdPrefix, data.Id)
	contestProblemInfoProblemIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoProblemIdPrefix, data.ProblemId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, contestProblemInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProblemId, data.ContestId)
	}, contestProblemInfoContestIdProblemIdKey, contestProblemInfoIdKey, contestProblemInfoProblemIdKey)
	return ret, err
}

func (m *defaultContestProblemInfoModel) Update(ctx context.Context, newData *ContestProblemInfo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	contestProblemInfoContestIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheContestProblemInfoContestIdProblemIdPrefix, data.ContestId, data.ProblemId)
	contestProblemInfoIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoIdPrefix, data.Id)
	contestProblemInfoProblemIdKey := fmt.Sprintf("%s%v", cacheContestProblemInfoProblemIdPrefix, data.ProblemId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, contestProblemInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ProblemId, newData.ContestId, newData.Id)
	}, contestProblemInfoContestIdProblemIdKey, contestProblemInfoIdKey, contestProblemInfoProblemIdKey)
	return err
}

func (m *defaultContestProblemInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheContestProblemInfoIdPrefix, primary)
}

func (m *defaultContestProblemInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", contestProblemInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultContestProblemInfoModel) tableName() string {
	return m.table
}
