// Code generated by goctl. DO NOT EDIT.
// Source: test.proto

package testclient

import (
	"context"

	"YunOJ/services/test/rpc/test"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetOneReq  = test.GetOneReq
	GetOneResp = test.GetOneResp

	Test interface {
		GetOne(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error)
	}

	defaultTest struct {
		cli zrpc.Client
	}
)

func NewTest(cli zrpc.Client) Test {
	return &defaultTest{
		cli: cli,
	}
}

func (m *defaultTest) GetOne(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error) {
	client := test.NewTestClient(m.cli.Conn())
	return client.GetOne(ctx, in, opts...)
}
